name: test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-library:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./woodland
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: "26.0.2"
          gleam-version: "1.1.0"
          rebar3-version: "3"
      - run: gleam deps download
      - run: gleam test
      - run: gleam format --check src test
  test-client:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./woodland-client
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: "26.0.2"
          gleam-version: "1.1.0"
          rebar3-version: "3"
      - run: gleam deps download
      - run: gleam test
      - run: gleam format --check src test
  test-server:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./woodland-server
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: "26.0.2"
          gleam-version: "1.1.0"
          rebar3-version: "3"
      - run: gleam deps download
      - run: gleam test
      - run: gleam format --check src test
