name: test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-library:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: "26.0.2"
          gleam-version: "1.2.1"
          rebar3-version: "3"
      - run: gleam deps download
      - run: gleam test
        if: always()
      - run: gleam format --check src test
        if: always()
